import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import { getGame, getPlayer, getPlayerStats, getSchedule, getTeamInjuredList, getTeamRoster, getTeams, searchPitchers } from "./src/services/mlbApi";
import { getAnalyticsForDate, getGameAnalytics, getTodayAnalytics } from "./src/services/analytics";

function seasonStat(payload: any, group: 'hitting' | 'pitching') { const block=(payload?.stats??[]).find((item:any)=>item?.group?.displayName?.toLowerCase()===group||item?.group?.displayName?.toLowerCase().includes(group)); return block?.splits?.[0]?.stat??{}; }
async function startServer(){
 const app=express(); const PORT=3000; app.use(express.json());
 app.get('/api/games/today',async(_req,res)=>{try{res.json({games:await getSchedule(),updatedAt:new Date().toISOString()});}catch(error:any){res.status(502).json({error:error?.message||'Failed to load MLB schedule'});}});
 app.get('/api/teams',async(_req,res)=>{try{res.json({teams:await getTeams()});}catch(error:any){res.status(502).json({error:error?.message||'Failed to load MLB teams'});}});
 app.get('/api/players/search',async(req,res)=>{try{const query=String(req.query.q??'').trim();if(query.length<2)return res.json({players:[]});res.json({players:await searchPitchers(query)});}catch(error:any){res.status(502).json({error:error?.message||'Failed to search MLB pitchers'});}});
 app.get('/api/matchup-builder',async(req,res)=>{try{const pitcherId=Number(req.query.pitcherId),teamId=Number(req.query.teamId);if(!Number.isInteger(pitcherId)||!Number.isInteger(teamId))return res.status(400).json({error:'pitcherId and teamId are required'});const[pitcherInfo,pitcherStatsPayload,rosterPayload,injuredList,teams]=await Promise.all([getPlayer(pitcherId),getPlayerStats(pitcherId),getTeamRoster(teamId),getTeamInjuredList(teamId).catch(()=>[]),getTeams()]);const pitcherPerson=pitcherInfo?.people?.[0]??{},pitcherStats=seasonStat(pitcherStatsPayload,'pitching'),team=teams.find((x:any)=>x.id===teamId)??{id:teamId,name:'Selected Team'},hitters=(rosterPayload?.roster??[]).filter((e:any)=>e?.position?.type!=='Pitcher'&&e?.position?.abbreviation!=='P').slice(0,16);const batters=await Promise.all(hitters.map(async(entry:any)=>{const id=entry?.person?.id;if(!id)return null;try{const[playerPayload,statsPayload]=await Promise.all([getPlayer(id),getPlayerStats(id)]),person=playerPayload?.people?.[0]??entry.person??{},stats=seasonStat(statsPayload,'hitting');return{id,name:person.fullName??entry?.person?.fullName??'Unknown player',position:entry?.position?.abbreviation??person?.primaryPosition?.abbreviation??'',batSide:person?.batSide?.code??null,stats:{gamesPlayed:stats.gamesPlayed??null,atBats:stats.atBats??null,hits:stats.hits??null,homeRuns:stats.homeRuns??null,rbi:stats.rbi??null,strikeOuts:stats.strikeOuts??null,baseOnBalls:stats.baseOnBalls??null,avg:stats.avg??null,obp:stats.obp??null,slg:stats.slg??null,ops:stats.ops??null}};}catch{return{id,name:entry?.person?.fullName??'Unknown player',position:entry?.position?.abbreviation??'',batSide:null,stats:{}};}}));res.json({pitcher:{id:pitcherId,name:pitcherPerson.fullName??'Unknown pitcher',pitchHand:pitcherPerson?.pitchHand?.code??null,stats:{gamesPlayed:pitcherStats.gamesPlayed??null,gamesStarted:pitcherStats.gamesStarted??null,inningsPitched:pitcherStats.inningsPitched??null,era:pitcherStats.era??null,whip:pitcherStats.whip??null,strikeOuts:pitcherStats.strikeOuts??null,strikeoutsPer9Inn:pitcherStats.strikeoutsPer9Inn??null,walksPer9Inn:pitcherStats.walksPer9Inn??null}},team,batters:batters.filter(Boolean),injuredList});}catch(error:any){res.status(502).json({error:error?.message||'Failed to build pitcher vs team matchup'});}});
 app.get('/api/teams/:teamId/injured-list',async(req,res)=>{try{const teamId=Number(req.params.teamId);if(!Number.isInteger(teamId))return res.status(400).json({error:'Invalid teamId'});res.json({injuredList:await getTeamInjuredList(teamId),updatedAt:new Date().toISOString()});}catch(error:any){res.status(502).json({error:error?.message||'Failed to load injured list'});}});
 app.get('/api/games/:gamePk',async(req,res)=>{try{const gamePk=Number(req.params.gamePk);if(!Number.isInteger(gamePk))return res.status(400).json({error:'Invalid gamePk'});res.json(await getGame(gamePk));}catch(error:any){res.status(502).json({error:error?.message||'Failed to load MLB game'});}});
 app.get('/api/games/:gamePk/analytics',async(req,res)=>{try{const gamePk=Number(req.params.gamePk);if(!Number.isInteger(gamePk))return res.status(400).json({error:'Invalid gamePk'});res.json(await getGameAnalytics(gamePk));}catch(error:any){res.status(502).json({error:error?.message||'Failed to calculate matchup analytics'});}});
 app.get('/api/analytics/today',async(req,res)=>{try{const date=typeof req.query.date==='string'?req.query.date:undefined;res.json({games:date?await getAnalyticsForDate(date):await getTodayAnalytics(),date:date??null,updatedAt:new Date().toISOString()});}catch(error:any){res.status(502).json({error:error?.message||'Failed to calculate daily analytics'});}});
 app.get('/api/analytics/date',async(req,res)=>{try{const date=String(req.query.date??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({error:'date is required as YYYY-MM-DD'});res.json({games:await getAnalyticsForDate(date),date,updatedAt:new Date().toISOString()});}catch(error:any){res.status(502).json({error:error?.message||'Failed to calculate dated analytics'});}});
 app.get('/api/teams/:teamId/roster',async(req,res)=>{try{const teamId=Number(req.params.teamId);if(!Number.isInteger(teamId))return res.status(400).json({error:'Invalid teamId'});res.json(await getTeamRoster(teamId));}catch(error:any){res.status(502).json({error:error?.message||'Failed to load roster'});}});
 app.get('/api/players/:playerId',async(req,res)=>{try{const playerId=Number(req.params.playerId);if(!Number.isInteger(playerId))return res.status(400).json({error:'Invalid playerId'});res.json(await getPlayer(playerId));}catch(error:any){res.status(502).json({error:error?.message||'Failed to load player'});}});
 app.get('/api/players/:playerId/stats',async(req,res)=>{try{const playerId=Number(req.params.playerId),season=req.query.season?Number(req.query.season):new Date().getFullYear();if(!Number.isInteger(playerId)||!Number.isInteger(season))return res.status(400).json({error:'Invalid playerId or season'});res.json(await getPlayerStats(playerId,season));}catch(error:any){res.status(502).json({error:error?.message||'Failed to load player stats'});}});
 app.post('/api/scout-report',async(req,res)=>{try{const{playerName,team,opponent,position,extraPrompt,stats}=req.body,apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return res.status(503).json({error:'GEMINI_API_KEY is not configured.'});const ai=new GoogleGenAI({apiKey});const prompt=`You are ScoutCore AI, an MLB scouting analyst. Generate a concise scouting report for ${playerName||'the selected player'} (${team||'unknown team'}) against ${opponent||'upcoming opponents'}.\nPosition: ${position||'unknown'}\nVerified MLB data supplied to you:\n${JSON.stringify(stats??{},null,2)}\nAdditional Context: ${extraPrompt||'Evaluate relevant performance, matchup, pitch, and batted-ball tendencies.'}\nDo not invent statistics.`;const response=await ai.models.generateContent({model:'gemini-2.5-flash',contents:prompt});res.json({report:response.text||'Report generated successfully.'});}catch(error:any){res.status(500).json({error:error?.message||'Failed to generate report'});}});
 if(process.env.NODE_ENV!=='production'){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}else{const distPath=path.join(process.cwd(),'dist');app.use(express.static(distPath));app.get('*all',(_req,res)=>res.sendFile(path.join(distPath,'index.html')));}app.listen(PORT,'0.0.0.0',()=>console.log(`ScoutCore server running on http://localhost:${PORT}`));
}
startServer();
