import React, { useEffect, useMemo, useState } from 'react';

type Range = 'TODAY' | 'YESTERDAY' | 'LAST 3 DAYS';
const dateKey = (offset=0) => { const d=new Date(); d.setDate(d.getDate()+offset); return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(d); };
async function fetchJson(url:string){const response=await fetch(url);if(!response.ok)throw new Error(`MLB request failed (${response.status})`);return response.json();}
function buildRows(feed:any,date:string){const rows:any[]=[];const gamePk=feed?.gameData?.game?.pk??feed?.gamePk;const venue=feed?.gameData?.venue?.name??'—';const teams=feed?.liveData?.boxscore?.teams??{};(['away','home'] as const).forEach(side=>{const block=teams?.[side]??{};const team=block?.team?.name??feed?.gameData?.teams?.[side]?.name??'Unknown Team';const players=Object.values(block?.players??{}) as any[];for(const p of players){const batting=p?.stats?.batting;if(batting&&Number(batting.plateAppearances??0)>0){const hits=Number(batting.hits??0),hr=Number(batting.homeRuns??0),rbi=Number(batting.rbi??0),bb=Number(batting.baseOnBalls??0),tb=Number(batting.totalBases??0),so=Number(batting.strikeOuts??0),ab=Number(batting.atBats??0);const index=Math.max(0,Math.min(100,Math.round(45+hits*9+hr*16+rbi*5+bb*3+tb*1.5-so*2)));rows.push({id:`${date}-${gamePk}-h-${p.person?.id}`,date,player:p.person?.fullName??'Unknown',team,type:'HITTER',index,venue,summary:`${hits} H · ${hr} HR · ${rbi} RBI`,detail:`${ab} AB · ${bb} BB · ${so} SO · ${tb} TB`});}const pitching=p?.stats?.pitching;if(pitching&&Number.parseFloat(String(pitching.inningsPitched??'0'))>0){const ip=Number.parseFloat(String(pitching.inningsPitched??'0'))||0,k=Number(pitching.strikeOuts??0),er=Number(pitching.earnedRuns??0),h=Number(pitching.hits??0),bb=Number(pitching.baseOnBalls??0);const index=Math.max(0,Math.min(100,Math.round(50+ip*5+k*4-er*9-h*2-bb*2)));rows.push({id:`${date}-${gamePk}-p-${p.person?.id}`,date,player:p.person?.fullName??'Unknown',team,type:'PITCHER',index,venue,summary:`${pitching.inningsPitched} IP · ${k} K · ${er} ER`,detail:`${h} H · ${bb} BB · ${pitching.numberOfPitches??'—'} P`});}}});return rows;}

export const AnalyticsView:React.FC=()=>{const [range,setRange]=useState<Range>('YESTERDAY');const [games,setGames]=useState<any[]>([]);const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
const dates=useMemo(()=>range==='TODAY'?[dateKey(0)]:range==='YESTERDAY'?[dateKey(-1)]:[dateKey(-1),dateKey(-2),dateKey(-3)],[range]);
const load=async()=>{setLoading(true);setError(null);try{const schedules=await Promise.all(dates.map(async date=>({date,data:await fetchJson(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${date}`)})));const gameList=schedules.flatMap(({date,data})=>(data?.dates??[]).flatMap((d:any)=>(d.games??[]).map((g:any)=>({...g,_date:date}))));setGames(gameList);const feeds=await Promise.all(gameList.map((g:any)=>fetchJson(`https://statsapi.mlb.com/api/v1.1/game/${g.gamePk}/feed/live`).then(feed=>({feed,date:g._date})).catch(()=>null)));setRows(feeds.filter(Boolean).flatMap((x:any)=>buildRows(x.feed,x.date)).sort((a:any,b:any)=>b.index-a.index));}catch(err){setError(err instanceof Error?err.message:'Unable to load analytics.');setRows([]);}finally{setLoading(false);}};
useEffect(()=>{load();const timer=window.setInterval(load,10*60*1000);return()=>window.clearInterval(timer);},[range]);
const avgIndex=useMemo(()=>rows.length?rows.reduce((s,r)=>s+r.index,0)/rows.length:null,[rows]);const hitterCount=rows.filter(r=>r.type==='HITTER').length;const pitcherCount=rows.filter(r=>r.type==='PITCHER').length;const standoutCount=rows.filter(r=>r.index>=75).length;const heading=range==='TODAY'?'Best verified performances today':range==='YESTERDAY'?"Yesterday's best verified performances":'Best verified performances from the last 3 days';
return <div className="min-h-screen bg-[#0b1326] text-[#dae2fd] p-8 space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><span className="font-label-caps text-xs text-[#65f2b5]">VERIFIED MLB DATA</span><h1 className="font-display-lg text-4xl">Advanced Analytics</h1><p className="text-sm text-[#849495] mt-1">Verified MLB performance analytics from live and completed games.</p></div><div className="flex gap-1 bg-[#131b2e] p-1.5 rounded-xl self-start">{(['TODAY','YESTERDAY','LAST 3 DAYS'] as Range[]).map(item=><button key={item} onClick={()=>setRange(item)} className={`px-4 py-2 rounded-lg text-xs font-bold ${range===item?'bg-[#00f0ff] text-[#00363a]':'text-[#aeb9c2] hover:text-white'}`}>{item}</button>)}</div></div>{error&&<div className="p-4 rounded-xl border border-[#ffb4ab]/30 bg-[#ffb4ab]/10 text-[#ffb4ab]">{error}</div>}<div className="grid grid-cols-1 md:grid-cols-5 gap-4"><Metric label="GAMES" value={games.length}/><Metric label="HITTERS" value={hitterCount}/><Metric label="PITCHERS" value={pitcherCount}/><Metric label="STANDOUTS" value={standoutCount}/><Metric label="AVG INDEX" value={avgIndex===null?'—':avgIndex.toFixed(1)}/></div><div className="bg-[#171f33] rounded-xl border border-[#3b494b]/20 p-5"><div className="flex justify-between items-center mb-4"><div><span className="text-[10px] text-[#849495]">TOP PERFORMANCE SIGNALS</span><h2 className="font-headline-lg text-xl">{heading}</h2></div><button onClick={load} className="text-xs text-[#00f0ff]">REFRESH</button></div>{loading?<p className="text-sm text-[#849495]">Loading MLB analytics…</p>:<div className="space-y-3">{rows.slice(0,30).map((row:any,index:number)=><div key={row.id} className="bg-[#131b2e] p-4 rounded-lg border border-[#3b494b]/15"><div className="grid grid-cols-[34px_1fr_auto] items-center gap-3"><span className="text-xs text-[#849495]">#{index+1}</span><div><p className="text-sm font-bold">{row.player} <span className="text-[10px] text-[#00f0ff] ml-2">{row.type}</span></p><p className="text-xs text-[#849495]">{row.team} · {row.venue}{range==='LAST 3 DAYS'?` · ${row.date}`:''}</p><p className="text-sm text-[#d5ddec] mt-1 font-data-numeric">{row.summary}</p><p className="text-xs text-[#849495] mt-1">{row.detail}</p></div><div className="text-right"><p className="text-[9px] text-[#849495]">INDEX</p><p className="font-data-numeric text-2xl text-[#00f0ff]">{row.index}</p></div></div></div>)}{!rows.length&&<p className="text-sm text-[#849495]">No player performance data is available for this period yet.</p>}</div>}</div></div>};
const Metric=({label,value}:{label:string;value:React.ReactNode})=><div className="bg-[#171f33] rounded-xl border border-[#3b494b]/20 p-5"><span className="text-[10px] text-[#849495]">{label}</span><p className="font-data-numeric text-3xl font-bold text-[#dbfcff] mt-1">{value}</p></div>;
