import React, { useEffect, useMemo, useState } from 'react';
import { buildPitcherVsTeam, fetchPlayerCareerStats, fetchPlayerHittingHandSplits, fetchPlayerRecentGameLogs, fetchRecentPitchProfile, fetchTeams, searchMlbPitchers } from '../services/mlbClient';
import { mlbPlayerHeadshotUrl, mlbTeamLogoUrl } from '../services/mlbMedia';

export const CinematicMatchupView: React.FC = () => {
  const [teams,setTeams]=useState<any[]>([]); const [teamId,setTeamId]=useState<number|null>(null);
  const [q,setQ]=useState(''); const [results,setResults]=useState<any[]>([]); const [pitcher,setPitcher]=useState<any>(null);
  const [matchup,setMatchup]=useState<any>(null); const [batterId,setBatterId]=useState<number|null>(null);
  const [profile,setProfile]=useState<any[]>([]); const [career,setCareer]=useState<any>(null); const [splits,setSplits]=useState<any>(null);
  const [pLogs,setPLogs]=useState<any[]>([]); const [bLogs,setBLogs]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{fetchTeams().then(x=>{setTeams(x);setTeamId(x[0]?.id??null)}).catch(()=>setError('Unable to load MLB teams.'))},[]);
  useEffect(()=>{if(q.trim().length<2||pitcher){setResults([]);return} const t=setTimeout(()=>searchMlbPitchers(q).then(setResults).catch(()=>setResults([])),250); return()=>clearTimeout(t)},[q,pitcher]);
  const selectedBatter=useMemo(()=>matchup?.batters?.find((b:any)=>b.id===batterId)??null,[matchup,batterId]);
  const build=async()=>{if(!pitcher||!teamId)return;setLoading(true);setError(null);setBatterId(null);try{const m=await buildPitcherVsTeam(pitcher.id,teamId);setMatchup(m);const [pp,logs]=await Promise.all([fetchRecentPitchProfile(pitcher.id,3).catch(()=>[]),fetchPlayerRecentGameLogs(pitcher.id,'pitching',10).catch(()=>[])]);setProfile(pp);setPLogs(logs)}catch(e){setError(e instanceof Error?e.message:'Unable to build matchup.')}finally{setLoading(false)}};
  useEffect(()=>{if(!batterId){setCareer(null);setSplits(null);setBLogs([]);return} Promise.all([fetchPlayerCareerStats(batterId,'hitting').catch(()=>null),fetchPlayerHittingHandSplits(batterId).catch(()=>null),fetchPlayerRecentGameLogs(batterId,'hitting',10).catch(()=>[])]).then(([c,s,l])=>{setCareer(c);setSplits(s);setBLogs(l)})},[batterId]);
  const advantage=selectedBatter?calcAdvantage(matchup?.pitcher,selectedBatter,splits):null;
  return <div className="min-h-screen bg-[#08111f] text-[#dae2fd] p-6 lg:p-8 space-y-6">
    <section className="bg-[#10192b] border border-[#26364e] rounded-xl p-5"><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-5"><div><p className="font-label-caps text-[10px] text-[#54dce9]">PITCHER VS BATTER</p><h1 className="font-display-lg text-3xl mt-1">Matchup Intelligence</h1></div><div className="grid grid-cols-1 md:grid-cols-[1fr_auto_1fr_auto] gap-3 items-end flex-1 max-w-4xl"><div className="relative"><label className="text-[9px] text-[#849495] font-label-caps">CHOOSE PITCHER</label><input className="mt-2 w-full bg-[#151f33] border border-[#30415c] rounded-md px-3 py-2.5 text-sm" value={pitcher?pitcher.name:q} onChange={e=>{setPitcher(null);setQ(e.target.value)}} placeholder="Search pitcher..."/>{results.length>0&&<div className="absolute z-30 w-full mt-1 max-h-56 overflow-auto bg-[#151f33] border border-[#30415c] rounded-md">{results.map(p=><button key={p.id} onClick={()=>{setPitcher(p);setQ(p.name);setResults([])}} className="w-full p-3 text-left hover:bg-[#202c43] text-sm">{p.name} <span className="text-[#849495] text-xs">{p.pitchHand?`· ${p.pitchHand}HP`:''}</span></button>)}</div>}</div><span className="pb-2 text-[#54dce9] font-bold">VS</span><div><label className="text-[9px] text-[#849495] font-label-caps">CHOOSE TEAM</label><select className="mt-2 w-full bg-[#151f33] border border-[#30415c] rounded-md px-3 py-2.5 text-sm" value={teamId??''} onChange={e=>setTeamId(Number(e.target.value))}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><button onClick={build} disabled={!pitcher||!teamId||loading} className="px-4 py-2.5 bg-[#56dce9] text-[#07151c] rounded-md text-xs font-bold disabled:opacity-40">{loading?'BUILDING…':'BUILD'}</button></div></div></section>
    {error&&<div className="p-4 rounded-lg border border-[#ff8d8d]/30 bg-[#ff8d8d]/10 text-[#ffb4ab] text-sm">{error}</div>}
    {matchup&&!selectedBatter&&<Roster matchup={matchup} choose={setBatterId}/>} 
    {matchup&&selectedBatter&&<>
      <div className="grid grid-cols-1 xl:grid-cols-[1fr_220px_1fr] gap-5 items-stretch">
        <PlayerPanel type="pitcher" player={matchup.pitcher} profile={profile}/>
        <CenterAdvantage pitcher={matchup.pitcher} batter={selectedBatter} value={advantage}/>
        <PlayerPanel type="batter" player={selectedBatter} career={career} splits={splits}/>
      </div>
      <section className="bg-[#10192b] border border-[#26364e] rounded-xl overflow-hidden"><div className="px-4 py-3 border-b border-[#26364e]"><p className="font-label-caps text-[9px] text-[#849495]">OTHER BATTERS</p><h3 className="font-bold text-sm">Click another hitter to compare instantly</h3></div><RosterTable batters={matchup.batters} choose={setBatterId} selected={batterId}/></section>
      <Logs pitcher={matchup.pitcher} batter={selectedBatter} pLogs={pLogs} bLogs={bLogs}/>
      <Injured matchup={matchup}/>
    </>}
  </div>
}

const Roster=({matchup,choose}:any)=><section className="bg-[#10192b] border border-[#26364e] rounded-xl overflow-hidden"><div className="p-4 flex items-center gap-3 border-b border-[#26364e]"><div className="w-12 h-12 bg-white rounded-md p-1.5"><img src={mlbTeamLogoUrl(matchup.team.id)} className="w-full h-full object-contain"/></div><div><p className="text-[9px] text-[#849495] font-label-caps">CHOOSE A BATTER</p><h2 className="font-display-lg text-xl">{matchup.team.name}</h2></div></div><RosterTable batters={matchup.batters} choose={choose}/></section>;
const RosterTable=({batters,choose,selected}:any)=><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-xs"><thead className="bg-[#08111f] text-[#849495]"><tr><th className="p-3 text-left">BATTER</th><th>BATS</th><th>AB</th><th>R</th><th>H</th><th>HR</th><th>RBI</th><th>BB</th><th>SO</th><th>AVG</th><th>OBP</th><th>SLG</th></tr></thead><tbody>{batters.map((b:any)=><tr key={b.id} onClick={()=>choose(b.id)} className={`border-t border-[#26364e]/60 cursor-pointer hover:bg-[#17243a] ${selected===b.id?'bg-[#163348]':''}`}><td className="p-3"><div className="flex items-center gap-3"><Headshot id={b.id} name={b.name} small/><div><b>{b.name}</b><div className="text-[9px] text-[#849495]">{b.position}</div></div></div></td><td>{b.batSide??'—'}</td><td>{b.stats?.atBats??'—'}</td><td>{b.stats?.runs??'—'}</td><td>{b.stats?.hits??'—'}</td><td>{b.stats?.homeRuns??'—'}</td><td>{b.stats?.rbi??'—'}</td><td>{b.stats?.baseOnBalls??'—'}</td><td>{b.stats?.strikeOuts??'—'}</td><td>{b.stats?.avg??'—'}</td><td>{b.stats?.obp??'—'}</td><td>{b.stats?.slg??'—'}</td></tr>)}</tbody></table></div>;

const PlayerPanel=({type,player,profile,career,splits}:any)=>{const pitcher=type==='pitcher';const s=player.stats??{};return <section className={`bg-[#151f33] rounded-lg border border-[#26364e] ${pitcher?'border-l-2 border-l-[#54dce9]':'border-r-2 border-r-[#cbd7ef]'} p-5 min-h-[470px]`}><div className="flex items-start gap-4"><Headshot id={player.id} name={player.name}/><div className="min-w-0"><p className={`font-label-caps text-[9px] ${pitcher?'text-[#54dce9]':'text-[#cbd7ef]'}`}>{pitcher?'STARTING PITCHER':'SELECTED BATTER'}</p><h2 className="font-display-lg text-3xl leading-none mt-2">{player.name}</h2><p className="text-[10px] text-[#849495] mt-2">{pitcher?`${player.pitchHand??'?'}HP`:`${player.batSide??'?'}HB · ${player.position??''}`}</p></div></div>{pitcher?<><div className="grid grid-cols-3 gap-3 mt-7"><Data label="ERA" value={s.era}/><Data label="WHIP" value={s.whip}/><Data label="K/9" value={s.strikeoutsPer9Inn}/></div><div className="mt-6"><p className="font-label-caps text-[9px] text-[#849495]">ARSENAL DISTRIBUTION</p><div className="flex mt-3 h-8 overflow-hidden rounded-sm">{profile?.slice(0,4).map((p:any,i:number)=><div key={p.code} style={{width:`${Math.max(10,p.usagePct)}%`}} className={`${i===0?'bg-[#54dce9] text-[#07222a]':i===1?'bg-[#b9c8de] text-[#10192b]':'bg-[#2a3950]'} flex items-center justify-center text-[8px] font-bold`}>{p.code}</div>)}</div></div><div className="mt-6 text-xs leading-relaxed text-[#aab8ce]">{pitcherScout(player,profile)}</div></>:<><div className="mt-7"><p className="font-label-caps text-[9px] text-[#849495]">2026 REGULAR SEASON</p><div className="grid grid-cols-3 md:grid-cols-6 gap-2 mt-2">{[['AB',s.atBats],['AVG',s.avg],['HR',s.homeRuns],['RBI',s.rbi],['SB',s.stolenBases],['OPS',s.ops]].map(([l,v])=><Data key={l} label={l} value={v}/>)}</div></div><div className="mt-5"><p className="font-label-caps text-[9px] text-[#849495]">CAREER REGULAR SEASON</p><div className="grid grid-cols-3 md:grid-cols-6 gap-2 mt-2">{[['AB',career?.atBats],['AVG',career?.avg],['HR',career?.homeRuns],['RBI',career?.rbi],['SB',career?.stolenBases],['OPS',career?.ops]].map(([l,v])=><Data key={l} label={l} value={v}/>)}</div></div><div className="mt-5 text-xs leading-relaxed text-[#aab8ce]">{batterScout(player,splits)}</div></>}</section>};
const CenterAdvantage=({pitcher,batter,value}:any)=><section className="flex flex-col items-center justify-center text-center px-2"><p className="font-label-caps text-[9px] text-[#849495]">ADVANTAGE</p><div className="relative w-28 h-28 mt-4 rounded-full flex items-center justify-center"><div className="absolute inset-0 rounded-full border-[5px] border-[#26364e]"/><div className="absolute inset-0 rounded-full border-[5px] border-transparent border-t-[#54dce9] border-r-[#54dce9] animate-spin [animation-duration:4s]"/><div><div className="font-data-numeric text-3xl">{value??50}%</div><div className="text-[8px] text-[#54dce9] font-label-caps">{(value??50)>=50?'PITCHER':'BATTER'}</div></div></div><span className="material-symbols-outlined text-[#54dce9] mt-5">swap_horiz</span><div className="mt-4 px-4 py-2 rounded-md bg-[#151f33] text-[9px] font-label-caps">{Math.abs((value??50)-50)>12?'HIGH LEVERAGE':'BALANCED'}</div><div className="mt-6"><p className="font-label-caps text-[8px] text-[#849495]">KEY FACTOR</p><p className="text-xs text-[#aab8ce] mt-2 leading-relaxed">{pitcher.pitchHand??'?'}HP vs {batter.batSide??'?'}HB. Current handedness splits and pitcher run-prevention profile shape this matchup index.</p></div></section>;
const Data=({label,value}:any)=><div className="bg-[#111a2c] p-3 rounded-md"><p className="font-label-caps text-[8px] text-[#849495]">{label}</p><p className="font-data-numeric text-lg mt-2">{value??'—'}</p><div className="h-0.5 w-8 bg-[#54dce9] mt-2"/></div>;
const Headshot=({id,name,small=false}:any)=><div className={`${small?'w-10 h-10':'w-20 h-20'} rounded-md bg-[#202b3f] overflow-hidden shrink-0`}><img src={mlbPlayerHeadshotUrl(id,small?120:240)} alt={name} className="w-full h-full object-contain"/></div>;
const Logs=({pitcher,batter,pLogs,bLogs}:any)=><section className="grid grid-cols-1 xl:grid-cols-2 gap-5"><LogTable title={`${pitcher.name} recent games`} logs={pLogs} pitcher/><LogTable title={`${batter.name} recent games`} logs={bLogs}/></section>;
const LogTable=({title,logs,pitcher=false}:any)=><div className="bg-[#10192b] border border-[#26364e] rounded-xl overflow-hidden"><div className="p-4 border-b border-[#26364e]"><p className="font-label-caps text-[9px] text-[#849495]">GAME LOGS</p><h3 className="font-bold text-sm">{title}</h3></div><table className="w-full text-xs"><thead className="bg-[#08111f] text-[#849495]"><tr><th className="p-3 text-left">DATE</th><th className="text-left">OPP</th>{pitcher?<><th>IP</th><th>K</th><th>ER</th></>:<><th>AB</th><th>H</th><th>HR</th><th>RBI</th></>}</tr></thead><tbody>{logs.map((x:any,i:number)=><tr key={i} className="border-t border-[#26364e]/50"><td className="p-3">{x.date?.slice(5)??'—'}</td><td>{x.opponent??'—'}</td>{pitcher?<><td>{x.stat?.inningsPitched??'—'}</td><td>{x.stat?.strikeOuts??'—'}</td><td>{x.stat?.earnedRuns??'—'}</td></>:<><td>{x.stat?.atBats??'—'}</td><td>{x.stat?.hits??'—'}</td><td>{x.stat?.homeRuns??'—'}</td><td>{x.stat?.rbi??'—'}</td></>}</tr>)}</tbody></table></div>;
const Injured=({matchup}:any)=><section className="bg-[#10192b] border border-[#ff8d8d]/20 rounded-xl overflow-hidden"><div className="p-4 border-b border-[#ff8d8d]/15"><p className="font-label-caps text-[9px] text-[#ff9b9b]">INJURED LIST</p><h3 className="font-bold text-sm">{matchup.team.name}</h3></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 p-4">{matchup.injuredList?.length?matchup.injuredList.map((p:any)=><div key={p.id} className="flex items-center gap-3 bg-[#151f33] p-3 rounded-md"><Headshot id={p.id} name={p.name} small/><div><b className="text-sm">{p.name}</b><div className="text-[9px] text-[#849495]">{p.position} · {p.status}</div></div></div>):<p className="text-xs text-[#849495]">No injured-list players returned.</p>}</div></section>;
const calcAdvantage=(p:any,b:any,splits:any)=>{let v=50;const era=Number(p?.stats?.era);const k9=Number(p?.stats?.strikeoutsPer9Inn);if(Number.isFinite(era))v+=(4-era)*4;if(Number.isFinite(k9))v+=(k9-8)*2;const opp=p?.pitchHand==='L'?splits?.vsLeft:splits?.vsRight;const ops=Number(opp?.ops);if(Number.isFinite(ops))v-=(ops-.720)*30;return Math.max(20,Math.min(80,Math.round(v)))};
const pitcherScout=(p:any,profile:any[])=>{const top=profile?.[0];return top?`${p.name} works primarily off the ${top.name}, averaging ${top.avgVelo.toFixed(1)} mph in recent tracked outings with ${top.usagePct.toFixed(0)}% usage. His 2026 profile is ${p.stats?.era??'—'} ERA, ${p.stats?.whip??'—'} WHIP and ${p.stats?.strikeoutsPer9Inn??'—'} K/9.`:`${p.name} has a ${p.stats?.era??'—'} ERA and ${p.stats?.whip??'—'} WHIP in 2026.`};
const batterScout=(b:any,s:any)=>{const side=b.batSide==='L'?'left-handed':b.batSide==='R'?'right-handed':'switch';const l=s?.vsLeft,r=s?.vsRight; if(l?.ops&&r?.ops)return `${b.name} is a ${side} hitter. In 2026 he has produced a ${l.ops} OPS against left-handed pitching and ${r.ops} against right-handed pitching, giving the matchup context beyond the basic platoon label.`;return `${b.name} is a ${side} hitter with a ${b.stats?.avg??'—'} AVG and ${b.stats?.ops??'—'} OPS in 2026.`};
