import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from '../services/supabaseClient';

type Mode='weekly_h2h'|'same_game'|'team_up';
type Friend={profile_id:string;display_name:string;avatar_url?:string|null;scout_level?:string|null};
type Challenge={challenge_id:string;role:'inviter'|'invitee';other_profile_id:string;other_display_name:string;other_avatar_url?:string|null;mode?:Mode|null;inviter_preference?:Mode|null;invitee_preference?:Mode|null;status:string;created_at:string;updated_at:string};
const modes:{id:Mode;icon:string;title:string;sub:string}[]=[
 {id:'weekly_h2h',icon:'⚔️',title:'Weekly Head-to-Head',sub:'Compare your normal weekly predictions.'},
 {id:'same_game',icon:'⚾',title:'Same Game: You vs Friend',sub:'Predict the same MLB game privately, then compare.'},
 {id:'team_up',icon:'🤝',title:'Team Up',sub:'Predict the same MLB game together and reveal matched picks.'},
];
const modeName=(m?:Mode|null)=>modes.find(x=>x.id===m)?.title||'Friends Challenge';

export const FriendsChallengeView:React.FC<{onBack:()=>void}>=({onBack})=>{
 const [friends,setFriends]=useState<Friend[]>([]); const [challenges,setChallenges]=useState<Challenge[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [selected,setSelected]=useState<Friend|null>(null); const [view,setView]=useState<'play'|'inbox'|'active'>('play');
 const load=async()=>{if(!supabase){setLoading(false);return;}const[f,c]=await Promise.all([supabase.rpc('get_friend_challenge_friends'),supabase.rpc('get_my_friend_challenges')]);if(!f.error)setFriends((f.data??[]) as Friend[]);if(!c.error)setChallenges((c.data??[]) as Challenge[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const incoming=useMemo(()=>challenges.filter(c=>c.role==='invitee'&&c.status==='pending'),[challenges]);
 const active=useMemo(()=>challenges.filter(c=>['choosing','negotiating','accepted'].includes(c.status)),[challenges]);
 const send=async(mode?:Mode)=>{if(!supabase||!selected)return;setBusy('send');const{error}=await supabase.rpc('create_friend_challenge',{p_profile_id:selected.profile_id,p_mode:mode??null});if(!error){setSelected(null);setView('active');await load()}setBusy(null)};
 const respond=async(id:string,response:'accept'|'decline')=>{if(!supabase)return;setBusy(id);await supabase.rpc('respond_friend_challenge',{p_challenge_id:id,p_response:response});await load();setBusy(null)};
 const prefer=async(id:string,mode:Mode)=>{if(!supabase)return;setBusy(id);await supabase.rpc('set_friend_challenge_preference',{p_challenge_id:id,p_mode:mode});await load();setBusy(null)};
 const randomize=async(id:string)=>{if(!supabase)return;setBusy(id);await supabase.rpc('randomize_friend_challenge_mode',{p_challenge_id:id});await load();setBusy(null)};
 return <div className="min-h-screen bg-[#081225] px-4 py-5 text-[#dae2fd] sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl">
  <div className="flex items-center gap-3"><button onClick={onBack} className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#2d4059] bg-[#101a2d] text-white"><span className="material-symbols-outlined">arrow_back</span></button><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-[#65f2b5]">Free · 0 tickets</div><h1 className="text-2xl font-black text-white sm:text-3xl">Friends Challenge</h1><p className="text-xs text-[#8fa0b5]">No private typing. ScoutBot handles invitations and choices.</p></div></div>
  <div className="mt-5 grid grid-cols-3 overflow-hidden rounded-xl border border-[#2a405b] bg-[#0d1728]">{([['play','PLAY'],['inbox',`INVITES${incoming.length?` (${incoming.length})`:''}`],['active',`ACTIVE${active.length?` (${active.length})`:''}`]] as const).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`px-3 py-3 text-xs font-black ${view===id?'bg-[#00e6f4]/12 text-[#59e8f3]':'text-[#8fa0b5]'}`}>{label}</button>)}</div>
  {loading?<div className="py-20 text-center text-sm text-[#8fa0b5]">Loading Friends Challenge…</div>:<div className="mt-5">
   {view==='play'&&<><section className="rounded-2xl border border-[#2a405b] bg-[#101a2d] p-5"><h2 className="text-lg font-black text-white">Choose a friend</h2><p className="mt-1 text-xs text-[#8fa0b5]">Friends are people who follow each other.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{friends.length?friends.map(f=><button key={f.profile_id} onClick={()=>setSelected(f)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${selected?.profile_id===f.profile_id?'border-[#59e8f3] bg-[#00e6f4]/8':'border-[#2b3e58] bg-[#0c1627]'}`}><div className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full bg-[#59e8f3]/12 text-sm font-black text-[#59e8f3]">{f.avatar_url?<img src={f.avatar_url} className="h-full w-full object-cover"/>:f.display_name.slice(0,2).toUpperCase()}</div><div className="min-w-0"><div className="truncate font-bold text-white">{f.display_name}</div><div className="text-[10px] uppercase tracking-wide text-[#65f2b5]">{f.scout_level||'Rookie Scout'}</div></div></button>):<div className="text-sm text-[#8fa0b5]">You need a mutual friend before you can send a Friends Challenge.</div>}</div></section>
   {selected&&<section className="mt-4 rounded-2xl border border-[#2a405b] bg-[#101a2d] p-5"><div className="text-xs font-black uppercase tracking-[.14em] text-[#59e8f3]">Challenge {selected.display_name}</div><div className="mt-4 grid gap-3 md:grid-cols-3">{modes.map(m=><button key={m.id} onClick={()=>void send(m.id)} disabled={busy==='send'} className="rounded-xl border border-[#2b3e58] bg-[#0c1627] p-4 text-left hover:border-[#59e8f3]/60"><div className="text-2xl">{m.icon}</div><div className="mt-2 font-black text-white">{m.title}</div><div className="mt-1 text-xs text-[#8fa0b5]">{m.sub}</div><div className="mt-3 text-[10px] font-black text-[#65f2b5]">QUICK CHALLENGE</div></button>)}</div><button onClick={()=>void send()} disabled={busy==='send'} className="mt-3 w-full rounded-xl border border-[#59e8f3]/50 bg-[#00e6f4]/7 px-4 py-3 text-sm font-black text-[#59e8f3]">🤖 PLAY TOGETHER — LET SCOUTBOT ASK BOTH OF US</button></section>}</>}
   {view==='inbox'&&<div className="space-y-4">{incoming.length?incoming.map(c=><section key={c.challenge_id} className="rounded-2xl border border-[#2a405b] bg-[#101a2d] p-5"><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#65f2b5]">🤖 ScoutBot</div><h3 className="mt-2 text-lg font-black text-white">{c.other_display_name} invited you to {c.mode?modeName(c.mode):'play a Friends Challenge'}.</h3><p className="mt-1 text-xs text-[#8fa0b5]">{c.mode?'Accept to start setting it up.':'Accept and ScoutBot will ask both of you which game mode you prefer.'}</p><div className="mt-4 flex gap-2"><button onClick={()=>void respond(c.challenge_id,'accept')} disabled={busy===c.challenge_id} className="rounded-xl bg-[#59e8f3] px-5 py-2.5 text-xs font-black text-[#07101f]">ACCEPT</button><button onClick={()=>void respond(c.challenge_id,'decline')} disabled={busy===c.challenge_id} className="rounded-xl border border-[#3a4b63] px-5 py-2.5 text-xs font-black text-[#aebbd0]">DECLINE</button></div></section>):<div className="rounded-2xl border border-dashed border-[#31445f] bg-[#0e192b] px-5 py-16 text-center text-sm text-[#8fa0b5]">No new challenge invitations.</div>}</div>}
   {view==='active'&&<div className="space-y-4">{active.length?active.map(c=><section key={c.challenge_id} className="rounded-2xl border border-[#2a405b] bg-[#101a2d] p-5"><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#65f2b5]">🤖 ScoutBot · {c.other_display_name}</div>{c.status==='choosing'&&<><h3 className="mt-2 text-lg font-black text-white">Which type of game do you prefer?</h3><p className="mt-1 text-xs text-[#8fa0b5]">Your choice is private until both of you choose.</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{modes.map(m=><button key={m.id} onClick={()=>void prefer(c.challenge_id,m.id)} disabled={busy===c.challenge_id} className="rounded-xl border border-[#2b3e58] bg-[#0c1627] px-3 py-3 text-xs font-black text-white">{m.icon} {m.title}</button>)}</div></>}{c.status==='negotiating'&&<><h3 className="mt-2 text-lg font-black text-white">You chose different games.</h3><p className="mt-1 text-xs text-[#8fa0b5]">Choose again, or let ScoutBot randomly choose between your two preferences.</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void prefer(c.challenge_id,'weekly_h2h')} className="rounded-xl border border-[#3a4b63] px-3 py-2 text-xs font-bold">TRY AGAIN</button><button onClick={()=>void randomize(c.challenge_id)} className="rounded-xl bg-[#59e8f3] px-4 py-2 text-xs font-black text-[#07101f]">🎲 RANDOM PICK</button></div></>}{c.status==='accepted'&&<><h3 className="mt-2 text-lg font-black text-white">{modeName(c.mode)} accepted ✓</h3><p className="mt-1 text-xs text-[#8fa0b5]">Both players are ready. The next step will be game selection and private picks.</p><div className="mt-4 rounded-xl border border-[#00e6f4]/40 bg-[#00e6f4]/6 px-4 py-3 text-sm font-black text-[#59e8f3]">0 tickets · Friends Challenge results stay separate from Weekly Challenge.</div></>}</section>):<div className="rounded-2xl border border-dashed border-[#31445f] bg-[#0e192b] px-5 py-16 text-center text-sm text-[#8fa0b5]">No active Friends Challenges yet.</div>}</div>}
  </div>}
 </div></div>;
};