import React, { useEffect, useMemo, useState } from 'react';
import { fetchLiveGameFeed } from '../services/mlbClient';
import { LiveGameExperienceV5 } from './LiveGameExperienceV5';
import { LiveBoxScorePanel } from './LiveBoxScorePanel';

type GameSelection={gamePk?:number;gameDate?:string;status?:string;detailedState?:string;awayTeam?:{id:number;name:string;abbreviation?:string};homeTeam?:{id:number;name:string;abbreviation?:string}};
type Props={selectedGame?:GameSelection|null;signedIn:boolean;userEmail?:string|null;onOpenAuth:()=>void;onExit:()=>void};
const readStoredGame=():GameSelection|null=>{try{const raw=window.sessionStorage.getItem('scoutcore:selected-game');return raw?JSON.parse(raw):null;}catch{return null;}};

export const LiveGameFullscreenV2:React.FC<Props>=({selectedGame,signedIn,userEmail,onOpenAuth,onExit})=>{
  const game=useMemo(()=>selectedGame?.gamePk?selectedGame:readStoredGame(),[selectedGame?.gamePk]);
  const[feed,setFeed]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[boxOpen,setBoxOpen]=useState(false);
  useEffect(()=>{if(!game?.gamePk){setLoading(false);return;}let cancelled=false;const load=async(quiet=false)=>{if(!quiet)setLoading(true);try{const data=await fetchLiveGameFeed(game.gamePk!);if(!cancelled){setFeed(data);setError(null);}}catch(err){if(!cancelled)setError(err instanceof Error?err.message:'Unable to load live game.');}finally{if(!cancelled&&!quiet)setLoading(false);}};void load();const timer=window.setInterval(()=>void load(true),12000);return()=>{cancelled=true;window.clearInterval(timer);};},[game?.gamePk]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key!=='Escape')return;if(boxOpen){setBoxOpen(false);return;}onExit();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[boxOpen,onExit]);
  const pitchToast=useMemo(()=>{const plays=feed?.liveData?.plays??{};const all=Array.isArray(plays?.allPlays)?plays.allPlays:[];const play=plays?.currentPlay??all[all.length-1]??null;const events=Array.isArray(play?.playEvents)?play.playEvents:[];const pitches=events.filter((event:any)=>event?.isPitch||event?.details?.isPitch);const event=pitches[pitches.length-1]??null;if(!event)return null;const speed=Number(event?.pitchData?.startSpeed);return{key:String(event?.playId??`${play?.atBatIndex??0}-${event?.index??pitches.length}`),number:pitches.length,label:event?.details?.call?.description??event?.details?.description??'Pitch',speed:Number.isFinite(speed)?`${speed.toFixed(1)} mph`:'',type:event?.details?.type?.description??''};},[feed]);
  if(!game?.gamePk)return <div className="fixed inset-0 z-[200] flex items-center justify-center bg-[#02060d] text-white"><button onClick={onExit} className="absolute right-5 top-5 flex h-11 w-11 items-center justify-center rounded-xl border border-[#40516b] bg-[#07101f]"><span className="material-symbols-outlined">close</span></button><div className="rounded-2xl border border-[#2b405b] bg-[#0d1727] p-8 text-center"><b>No live game selected</b><p className="mt-2 text-sm text-[#8fa0b7]">Choose a game first.</p></div></div>;
  return <div className="fixed inset-0 z-[200] overflow-hidden bg-[#02060d] text-[#dae2fd]"><div className="fixed right-4 top-3 z-[320] flex gap-2"><button onClick={()=>setBoxOpen(true)} title="Box score" aria-label="Open box score" className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#40516b] bg-[#07101f]/95 text-[#c8d4e2] shadow-xl hover:border-[#00e6f4] hover:text-white"><span className="material-symbols-outlined text-[19px]">table_chart</span></button><button onClick={onExit} title="Exit live game" aria-label="Exit live game" className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#40516b] bg-[#07101f]/95 text-[#c8d4e2] shadow-xl hover:border-[#00e6f4] hover:text-white"><span className="material-symbols-outlined">close</span></button></div>{loading&&!feed&&<div className="flex h-screen items-center justify-center text-sm text-[#9aa8bc]">Loading verified MLB live data…</div>}{error&&!feed&&<div className="flex h-screen items-center justify-center p-6 text-sm text-[#ffb4ab]">{error}</div>}{feed&&<LiveGameExperienceV5 gamePk={game.gamePk} feed={feed} signedIn={signedIn} userEmail={userEmail} onOpenAuth={onOpenAuth}/>} {pitchToast&&!boxOpen&&<div key={pitchToast.key} className="sc-live-pitch-toast fixed bottom-5 right-5 z-[315] flex min-w-[310px] max-w-[430px] items-center gap-3 rounded-xl border border-[#354757] bg-[#11191f]/96 px-4 py-3 text-white shadow-2xl backdrop-blur"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#3c7d26] text-base font-extrabold">{pitchToast.number}</span><div className="min-w-0"><p className="truncate text-base font-extrabold">{pitchToast.label}</p><p className="mt-0.5 truncate text-sm text-[#d2dbe0]">{[pitchToast.speed,pitchToast.type].filter(Boolean).join(' · ')}</p></div></div>}{boxOpen&&feed&&<LiveBoxScorePanel feed={feed} onClose={()=>setBoxOpen(false)}/>}</div>;
};
